GET http://localhost:3000/getvendorprofile

###

POST http://localhost:3000/updatevendorprofile
Content-Type: application/json

{
    "username" : "0000000006",
    "c_city" : "BI",
    "c_country" : "CO",
    "cf_name" : "JOHN",
    "cl_name" : "PIPER",
    "c_mobile" : "123456789",
    "c_pin" : "678956",
    "c_state" : "STA",
    "c_street" : "STR"
}